### ISSUE TITLE
SSL cert failure on VPN

### ISSUE THREAD

**Issue by rontho1992** [GeneralMills/pytrends#109]
When I try to login  using TrendReq(..) I am getting a SSL error. From what I've been able to figure out is that the form from `https://accounts.google.com/ServiceLogin` doesn't seem to accept the Passwd arguments until you make the request with the email and then you have to make a new request again with the password. Not sure if this is on the right track or I'm just being an idiot.

**Comment by dreyco676** [comment]
Do you have two-factor authentication turned on for that gmail account?

**Comment by rontho1992** [comment]
No and I have allow less secure apps on as I have used this account before for similar jobs

**Comment by dreyco676** [comment]
Ok, I'm having a hard time replicating. Are you on a VPN or using a proxy?

**Comment by rontho1992** [comment]
I'm on a VPN, assuming that might be causing the problem.

**Comment by dreyco676** [comment]
Yea, I'm not sure how to solve that unfortunately. If you find a solution or have suggestions feel free to let me know.

**Comment by rontho1992** [comment]
Will do, I used to run something similar to what you put together using Mechanize on AWS, but after Google did an update it started to fail. I'll play around with this some more and get back to you.

**Comment by dreyco676** [comment]
So I've been playing around with the auth stuff and I'm not even sure its needed. If I create another branch with it removed could you be willing to take a look?

**Comment by rontho1992** [comment]
Sure thing

**Comment by dreyco676** [comment]
Try the `no_auth` branch.

**Comment by rontho1992** [comment]
So that still gives a SSL error. I'm going to spin up an EC2 server and see if it's the firewall I'm behind that's blocking it or if it's when you are on VPN (I can browse to the Trends webpage, but maybe there's some black magic I'm not aware of). 

I'm leaning to it being a specific issue on my end as I checked my login logs for Google that I saw the login occurred, which suggests something funky over here.

**Comment by dreyco676** [comment]
Did you ever track down the issue?

**Comment by dreyco676** [comment]
I've gotten rid of authentication. Let me know if this issue still persists.

**Comment by Alescontrela** [comment]
Hi @dreyco676 , 

I'm not sure if it's an authentication issue. I tried using proxies with and without 2 factor authentication yet I still received the following SSL error: 

`HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /trends/api/explore?hl=en-US&tz=360&req=%7B%22comparisonItem%22%3A+%5B%7B%22keyword%22%3A+%22ripple%22%2C+%22time%22%3A+%222017-01-04T00+2017-01-11T00%22%2C+%22geo%22%3A+%22%22%7D%5D%2C+%22category%22%3A+0%2C+%22property%22%3A+%22%22%7D (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))`

It could perhaps be an issue with the proxy.
