### ISSUE TITLE
Time zone is not working

### ISSUE THREAD

**Issue by fabsig** [GeneralMills/pytrends#190]
Apparently, the argument tz is ignored by Google. Can somebody confirm this or tell me whether I am doing something wrong?

The following two requests give exactly the same data.

pytrends = TrendReq(hl='en-US', tz=-360)
kw_list = ["Blockchain"]
pytrends.build_payload(kw_list, cat=0, timeframe='today 3-m', geo='', gprop='')
pytrends.interest_over_time()

pytrends = TrendReq(hl='en-US', tz=360)
kw_list = ["Blockchain"]
pytrends.build_payload(kw_list, cat=0, timeframe='today 3-m', geo='', gprop='')
pytrends.interest_over_time()

**Comment by xleisj** [comment]
I can confirm that the tz argument is also not working for me.

However i found a workaround. You can transform the timestamps in your panda dataframe result to your preferred timezone:

result = interest_over_time_df = pytrend.interest_over_time()
index = result.index
cet = pytz.timezone('CET')
result.index = index.tz_localize(pytz.utc).tz_convert(cet)
print(result)

Then the timestamps are converted to CET

**Comment by zachokeeffe** [comment]
Cool hack, xleisj. Could you explain how that worked? I'm not terribly familiar with Python, but I found that, using that approach, the trend numbers do change. E.g., some test 'raw' results (regardless of tz):
            pizza isPartial
date                       
2016-12-14     55     False
2016-12-15     60     False
2016-12-16     79     False
2016-12-17    100     False
2016-12-18     93     False
2016-12-19     63     False
2016-12-20     59     False
2016-12-21     62     False

But after setting the timezone as you did with pytz:
                           pizza isPartial
date                                      
2016-12-14 01:00:00+01:00     54     False
2016-12-15 01:00:00+01:00     59     False
2016-12-16 01:00:00+01:00     78     False
2016-12-17 01:00:00+01:00    100     False
2016-12-18 01:00:00+01:00     95     False
2016-12-19 01:00:00+01:00     62     False
2016-12-20 01:00:00+01:00     58     False
2016-12-21 01:00:00+01:00     62     False

Is this actually correctly getting the daily hits from Google using the specified time zone, or is this some sort of interpolation trick? I ask because I've been trying to get time zone support from Google trends for some time to no avail. The URL requests give the same result regardless of the tz specified. For example, there is no timezone support in the [gtrendsR](https://github.com/PMassicotte/gtrendsR) package--the authors even [note in a comment](https://github.com/PMassicotte/gtrendsR/blob/master/R/zzz.R) that specifying a different timezone doesn't change the results, and after my own fiddling around, I found that, indeed, the json payload seems to ignore the timezone in the URL. Which makes me wonder what the 'default' timezone Google is using--I'm assuming UTC, which is what your code there seems to assume too, but I couldn't find any documentation confirming this.

**Comment by iprokin** [comment]
The issue is still present. It appears that no matter which `tz`, it returns UTC time.

**Comment by anndreh** [comment]
Yes, the same problem here. What are you guys doing to get around this?

**Comment by bibinhashley** [comment]
![image](https://user-images.githubusercontent.com/71463427/116369437-00783180-a827-11eb-9e51-63c0fe998af8.png)

Wherever the location is, google is calling it with tz=-330
