### ISSUE TITLE
TopCharts Issue

### ISSUE THREAD

**Issue by nxfxcom** [GeneralMills/pytrends#197]
Hello,

I am trying to run this simple script:
`from pytrends.request import TrendReq
pytrend = TrendReq()
top_charts_df = pytrend.top_charts(cid='actors', date=2017, geo='US-CA')
print(top_charts_df)
`

but i keep getting this error:
`Traceback (most recent call last):
  File "/Users/bsp/PycharmProjects/MacMini/TrendsByStateCat.py", line 8, in <module>
    top_charts_df = pytrend.top_charts(cid='actors', date=201710, geo='US-CA')
  File "/Users/bsp/anaconda/envs/MacMini/lib/python3.5/site-packages/pytrends/request.py", line 328, in top_charts
    params=chart_payload,
  File "/Users/bsp/anaconda/envs/MacMini/lib/python3.5/site-packages/pytrends/request.py", line 88, in _get_data
    'response with code {0}.'.format(response.status_code), response=response)
pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 404.
`

Any ideas why?

Thank you

**Comment by patchneranartkomol** [comment]
I believe you have to call top_charts with geo='US', which is the default parameter. I haven't been able to get this to work with geo='CA', since the CID's are totally different.

You can see how the API calls are made by examining the elements on the Google Trends Top Charts site: https://trends.google.com/trends/topcharts

**Comment by dreyco676** [comment]
I believe this has been resolved in a recent PR
