### ISSUE TITLE
Can only pull 80 days worth of daily data.

### ISSUE THREAD

**Issue by abmathewks** [GeneralMills/pytrends#21]
Every time I specify date="today 90-d", I don't get the fully ninety days of trend data for any term. Is this something to do with Google authentication or a bug in the library?

**Comment by abmathewks** [comment]
Here's an example of how I'm using it. Keys is something like baseball or football.

def GT_Daily_Run(keys):
    # connect to Google
    connector = pyGTrends(google_username, google_password)
    # make request
    connector.request_report(keys, date="today 90-d", geo="US")
    # wait a random amount of time between requests to avoid bot detection
    time.sleep(randint(5, 10))
    # download file
    connector.save_csv(path, '_' + "GT_Daily" + '_' + keys)

**Comment by dreyco676** [comment]
Hmm if I try different terms I get 88days. Still not 90. I'll look into this.

**Comment by dreyco676** [comment]
Ok I think I figured this out. Today is March 7th. If I use 'today 90-d' it actually does 2015-12-10 to 2016-03-08 which is 90days inclusive. This might be because it is already the 8th in UTC time. Google does not respect the user timezone for the today #-d.

If you are referring to blanks for the last 1-3 days Google seems to hold off on reporting those. Not much I can do.
