### ISSUE TITLE
Hourly data for more than 7 days isn't correctly dealt with

### ISSUE THREAD

**Issue by gbuchbi** [GeneralMills/pytrends#293]
When making different requests, Google Trends normalizes the data with regards to the highest datapoint inside each sample period.  Since 14 days of hourly data leads to 2 requests, each half of the request will be normalized based on the top hour of each of the two halves.

GeneralMills fixed this for daily data (see dailydata.py), but I not for hourly data, and the commits that fix other problems with hourly data (for example,  #288 ) don't seem to deal with this.

**Comment by Salompas** [comment]
Agreed. I was just looking at the same issue, and the function in requests.py just appends the fetched data to a list and returns it at the end. It might be possible to fix

**Comment by e-271** [comment]
So I created the #288 pull request, and this is an issue I've been grappling with and not found a good solution to. If anyone has any suggestions I'd be happy to implement them.

Google Trends API doesn't let you set the time-resolution you want, it decides the resolution based on how long the time period you give it is. For example if you want daily resolution, you have to request time periods somewhere between 1 week and 6 months. If you want 3 months of daily data, you have to loop through requesting 6 month intervals. 

The trouble is, like you said, what Google sends you is scaled to the maximum day within your request period. So at the edges between those 6 month intervals you will get a sudden spike. If you have 2 6-month intervals, you can stick them together, but the values are normalized on different scales, so a 100 on the first 6 months could be a 10 on the 2nd 6 months. 

I don't know a good solution to this problem. One idea might be that after you loop through intervals to get the data at the required resolution, you could also request the *entire timeperiod* which Google will give you at a lower resolution. Then you could find the peaks of each high-resolution interval, compare them to the lower-resolution graph, and do some math to re-scale. Seems like a big pain, but maybe worth it if you need this data. I wish Google would fix this issue though and allow us to request a certain time resolution, rather than us having to work around it in this way.

Let me know if you guys have any good ideas, I'd be happy to implement them as I would also like to see this issue fixed.

**Comment by e-271** [comment]
Hey, I didn't see that bit in dailydata.py when I was working on #288. I'll try and add that in.

**Comment by gbuchbi** [comment]
This issue also happens with daily data, and there seems to be two workarounds (I'll be giving examples with the time periods adapted to make sense with hourly data - the maximum number of days that you can ask to get hourly data is 7):
1) As used in the main branch. Let's say you want 14 days of hourly data.  Request from GT the first and the last 7. Then request another 7 days in the middle.  You can use these 7 days in the middle for which you have two GT requests for to scale.

2) As used in the pull request #294 : This example is can be easily explained with even 52 weeks of hourly data: Get each week individually, then make a request for the whole year (you will get the weekly index). Weight each individual week by the indices from the year request.

Of course, even after deciding on which of the two to follow, there are still questions on the details..

**Comment by e-271** [comment]
Okay, I rewrote dailydata.py so that it can deal with either hourly or daily data. Here's the file - you shouldn't need to clone my fork if you're not concerned with the other issues, I think you can simply copy this file and use it in the main repo:

https://github.com/e-271/pytrends/blob/master/pytrends/renormalize.py

**Comment by dreyco676** [comment]
We had multiple PR that got merged recently. Please review to see if they have fixed any of your concerns. If not please reopen the issue.

**Comment by liyuduan817** [comment]
> Okay, I rewrote dailydata.py so that it can deal with either hourly or daily data. Here's the file - you shouldn't need to clone my fork if you're not concerned with the other issues, I think you can simply copy this file and use it in the main repo:
> 
> https://github.com/e-271/pytrends/blob/master/pytrends/renormalize.py

when I use your setup, one problem occurred, TypeError: unsupported operand type(s) for -: 'datetime.date' and 'module',can you help me solve the problem?
