### ISSUE TITLE
Pytrends: The request failed: Google returned a response with code 429

### ISSUE THREAD

**Issue by therealjr** [GeneralMills/pytrends#321]
I'm getting a 429 response after my first request. Sat for several hours to see if this would go away but it has not. Is anyone else experiencing this? I made sure that pytrends is updated to the most recent version.

**Comment by kubilaykilinc** [comment]
I'm getting this error too. (with Example pytrends code)
pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 404.

**Comment by zar3bski** [comment]
Same here

**Comment by sq5rix** [comment]
I confirm. I get:
ConnectionError: HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /?geo=US (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f52805c62e8>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

**Comment by seyonechithrananda** [comment]
This may be because of a problem on the Google trends end or because max requests have been reached?

**Comment by sq5rix** [comment]
This is transient, fortunately! After few minutes, everything is back to normal

**Comment by seyonechithrananda** [comment]
@sq5rix Awesome! Must be that you hit max. requests to the Google Trends page. Usually cooldown is around 1 minute.
