### ISSUE TITLE
Set User agent string

### ISSUE THREAD

**Issue by cmabastar** [GeneralMills/pytrends#340]
Hi ,

Is there any way to set the user agent string? Would it help to avoid detection by google?

**Comment by emlazzarin** [comment]
Have you looked at the code? Since it uses the `requests` library, a quick search shows that it is straightforward to modify the user agent.

https://github.com/GeneralMills/pytrends/blob/master/pytrends/request.py

Are you having trouble with requests being rate-limited by Google? Do you have evidence it might help?

Thanks!

**Comment by flusa** [comment]
is there a way to modify the user-agent without change the source code from pytrends ?
i have some issue with google returning an error 500 after many 429 i think that update the user agent with different user may help
