### ISSUE TITLE
Update limit of keywords list

### ISSUE THREAD

**Issue by ilyinss** [GeneralMills/pytrends#485]
Hello.
Thank you for your library, its cool and very comfortable. When i used it, I find a small problem: limit of keywords list (possibly, its GoogleTrends limit). Limit equal 5 items in keywords list.
I fixed it with this code:

```
def chunks(lst, n):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i:i + n]
```
and then i use this function before pytrends.build_payload like this:

```
pytrends = TrendReq(hl='en-US', tz=360)

first = True
for chunk in list(chunks(mylist, 5)):
    clear_list = []
    for name in chunk:
    # build the payload
    pytrends.build_payload(kw_list = clear_list, timeframe='2020-01-01 2021-07-15', geo='RU')
    gdf = pytrends.interest_over_time()
    if first:
        all_gdf = gdf.copy()
        first = False
    else:
        all_gdf = pd.concat([all_gdf, gdf], axis = 1)
        all_gdf = all_gdf.drop('isPartial', axis = 1)
```

i think, you can add this small fix into loop like this:

```
if len(kw_list) <= 5:
    --normal way
else:
   --split list on chunks
```

Sergey.

**Comment by Salat23** [comment]
Not sure about the code chunk piece, but note that this way of splitting is incorrect. The reason is that each request returns normalized numbers in the 0-100 range. If we want to compare more than 5 keywords, we need to make requests which each contain one normalized category.

Imagine running requests for these EU country keywords:
```
mylist = ['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus', 'Czechia', 'Denmark',
  'Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'Ireland',
  'Italy', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Netherlands',
  'Poland', 'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden']
```
While `list(chunks(mylist, 5))` returns
```
[['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus'],
 ['Czechia', 'Denmark', 'Estonia', 'Finland', 'France'],
 ['Germany', 'Greece', 'Hungary', 'Ireland', 'Italy'],
 ['Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Netherlands'],
 ['Poland', 'Portugal', 'Romania', 'Slovakia', 'Slovenia'],
 ['Spain', 'Sweden']]
```
we actually need the following: `[ lst + [mylist[0]] for lst in list(chunks(mylist[1:], 4))]`
```
[['Belgium', 'Bulgaria', 'Croatia', 'Cyprus', 'Austria'],
 ['Czechia', 'Denmark', 'Estonia', 'Finland', 'Austria'],
 ['France', 'Germany', 'Greece', 'Hungary', 'Austria'],
 ['Ireland', 'Italy', 'Latvia', 'Lithuania', 'Austria'],
 ['Luxembourg', 'Malta', 'Netherlands', 'Poland', 'Austria'],
 ['Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Austria'],
 ['Spain', 'Sweden', 'Austria']]
```

This is, in some way, achieved by the [`_packTerms`](https://github.com/ecsalina/gtrends/blob/a782724ac5b60f8be568ebc8fba410d312ba14fc/gtrends.py#L190) method from the package `gtrends`, although that one has an issue that the first component is included twice in the chunked output.

**Comment by ilyinss** [comment]
Hello
Thanks a lot for correct way )
