### ISSUE TITLE
is that pytrends still unavailiable everyone? 

### ISSUE THREAD

**Issue by jimmywu9** [GeneralMills/pytrends#612]
IPython 8.15.0 -- An enhanced Interactive Python.

from pytrends.request import TrendReq

pytrends = TrendReq(hl='en-US', tz=360)

kw_list = ["Blockchain"]

pytrends.build_payload(kw_list, cat=0, timeframe='today 5-y', geo='TW', gprop='')

pytrends.interest_over_time()
Traceback (most recent call last):

  Cell In[5], line 1
    pytrends.interest_over_time()

  File ~\anaconda3\Lib\site-packages\pytrends\request.py:232 in interest_over_time
    req_json = self._get_data(

  File ~\anaconda3\Lib\site-packages\pytrends\request.py:159 in _get_data
    raise exceptions.TooManyRequestsError.from_response(response)

TooManyRequestsError: The request failed: Google returned a response with code 429

😢 is that just only my problem or its unavailable for everyone?

**Comment by AhmadKhanSenpai** [comment]
Not working even with proxies or even after using curl instead of just simple requests module. still getting this:
```pytrends.exceptions.TooManyRequestsError: The request failed: Google returned a response with code 429```
I am reading this module and I found out that basically its not actually getting the data from Google API instead its like they are webscraping or should I saying parsing the data from Google Trends and also its not accurate because google can detect its not human and it feeds it the inaccurate data, now they must have figure out what pytrend is actually doing and they have changed their backend. I don't know about networking I just have webscraping experience from scraping different kind of websites and even bypassing the cloudflare protection. I am looking to reverse engineer this package and make my own, there are other API's available that let you get the data of google trends for free but they have a limit. at least they are accurate though unlike google trends. Because its google after all no matter what you do they will still figure out what is happening on their server and they are gonna block us again.

**Comment by AhmadKhanSenpai** [comment]
As you can see I was right about google feeding the wrong or missing data:
https://github.com/GeneralMills/pytrends/issues/607#issue-2045454965

**Comment by xitvince** [comment]
Yes, it's possible that Google made some changes again.
I met the same issue.

**Comment by jimmywu9** [comment]
thanks all your reply
